In [1]:
from ffnn import FFNN
import numpy as np

In [ ]:
model = FFNN(layer_sizes=[5, 5, 5, 5, 10], activations=["sigmoid", "sigmoid", "sigmoid", "sigmoid"], weight_init="uniform", seed=42)

In [3]:
np.random.seed(42)
X_train = np.random.randn(100, 5)
y_train = np.random.randint(0, 2, size=(100, 1))
y_train_one_hot = np.eye(2)[y_train]

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("y_train_one_hot shape:", y_train_one_hot.shape)

X_train shape: (100, 5)
y_train shape: (100, 1)
y_train_one_hot shape: (100, 1, 2)


In [4]:
model.train(X=X_train, y=y_train, loss_function="mse")

epoch ke-0
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(3, 1)
(3, 1)
(1, 5)
(3, 5)
(3, 5)
(5, 5)
(3, 5)
(3, 5)
(5, 5)
Epoch 1/100 - Loss: 0.3350
epoch ke-1
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(3, 1)
(3, 1)
(1, 5)
(3, 5)
(3, 5)
(5, 5)
(3, 5)
(3, 5)
(5, 5)
Epoch 2/100 - Loss: 0.3470
epoch ke-2
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5, 5)
(3, 1)
(3, 1)
(1, 5)
(3, 5)
(3, 5)
(5, 5)
(3, 5)
(3, 5)
(5, 5)
Epoch 3/100 - Loss: 0.3344
epoch ke-3
(32, 1)
(32, 1)
(1, 5)
(32, 5)
(32, 5)
(5, 5)
(32, 5)
(32, 5)
(5,

[0.3350312402435509,
 0.3469689759839685,
 0.33435376069849215,
 0.3350200884560462,
 0.33468835847724615,
 0.3450404789805126,
 0.339845333625792,
 0.3348185252378108,
 0.3386505532237078,
 0.34345352379541,
 0.3379355008155105,
 0.3415976090803181,
 0.33706697677601055,
 0.3374519903616407,
 0.33118731193514217,
 0.33384608217579675,
 0.3338027177098743,
 0.33634611747041626,
 0.33941680882334696,
 0.3364377260129536,
 0.3314171247566841,
 0.3365253036634089,
 0.33199244505500264,
 0.33381943017449384,
 0.3341178843202188,
 0.3377225914850383,
 0.33720209057217837,
 0.33672200096215715,
 0.3335679027158001,
 0.3356364360687518,
 0.33378382080792734,
 0.33357031459422887,
 0.3334161745417197,
 0.3337584929443141,
 0.33377070951391424,
 0.33332190157069325,
 0.3334087694875641,
 0.3337795655705664,
 0.3328559914226341,
 0.3331964377967564,
 0.3330078256471081,
 0.33253312784057093,
 0.33453153534576896,
 0.33266378909405314,
 0.33180994955016535,
 0.33255324094029964,
 0.33208695650327

In [6]:
for layer in model.layers:
    print("=============")
    print(layer.weights)
    print(layer.biases)

[[-0.12692668  0.45118245  0.23061515  0.09864398 -0.34316816]
 [-0.34287969 -0.44227744  0.3672046   0.10113266  0.20747099]
 [-0.47965517  0.46998799  0.3321313  -0.28766694 -0.31800922]
 [-0.31526462 -0.19618613  0.02591188 -0.0680256  -0.20946824]
 [ 0.11159649 -0.36038123 -0.20819105 -0.13363527 -0.04377442]]
[[ 0.28746983 -0.30112722  0.01663021  0.09248065 -0.45486699]]
[[-0.12674745  0.45649663  0.23506272  0.10013595 -0.34813645]
 [-0.34474446 -0.4387119   0.36787296  0.10191805  0.20573261]
 [-0.48069217  0.47569037  0.33553153 -0.28617338 -0.32232235]
 [-0.31789985 -0.18986268  0.02789586 -0.06654163 -0.21299945]
 [ 0.11075992 -0.35547195 -0.20516415 -0.1323314  -0.0475153 ]]
[[ 0.28269315 -0.28910497  0.02021861  0.09529593 -0.46160028]]
[[-0.08160204]
 [ 0.49552479]
 [ 0.29026175]
 [ 0.14688316]
 [-0.31452804]]
[[-0.24413656]]


In [9]:
from sklearn.metrics import f1_score
y_prob = model.predict(np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]))

y_real = np.array([0, 0, 0, 0, 0])

y_pred = (y_prob >= 0.5).astype(int).flatten()

f1 = f1_score(y_real, y_pred, average='weighted')

print("F1 Score:", f1)

F1 Score: 1.0
